name: Build Android Bundle
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build GSons App
        run: |
          # 1. Package setup
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android
          
          # 2. Capacitor setup
          npx cap init "Al Mumin Guide" com.gsons.mumin --web-dir .
          npx cap add android
          npx cap sync android
          
          # 3. Build .aab (Bundle)
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

            - name: Upload .aab Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: "**/*.aab"
